# Generated by Django 2.2 on 2019-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term_Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(choices=[('open', 'open'), ('close', 'close')], default='open', max_length=32)),
                ('now_term', models.ForeignKey(on_delete=False, to='database_app.Term', to_field='term')),
            ],
        ),
    ]
