# Generated by Django 2.1.7 on 2019-04-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0002_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
